# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _linkedlist
else:
    import _linkedlist

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)



def Node_new(_value, _vsize):
    return _linkedlist.Node_new(_value, _vsize)

def Node_delete(_self):
    return _linkedlist.Node_delete(_self)

def LinkedList_new(_capacity):
    return _linkedlist.LinkedList_new(_capacity)

def LinkedList_delete(_self):
    return _linkedlist.LinkedList_delete(_self)

def LinkedList_deletet(_self):
    return _linkedlist.LinkedList_deletet(_self)

def LinkedList_append(_self, _node):
    return _linkedlist.LinkedList_append(_self, _node)

def LinkedList_appendt(_self, _node):
    return _linkedlist.LinkedList_appendt(_self, _node)

def LinkedList_appendv(_self, _value, _vsize):
    return _linkedlist.LinkedList_appendv(_self, _value, _vsize)

def LinkedList_appendvt(_self, _value, _vsize):
    return _linkedlist.LinkedList_appendvt(_self, _value, _vsize)

def LinkedList_push(_self, _node):
    return _linkedlist.LinkedList_push(_self, _node)

def LinkedList_pusht(_self, _node):
    return _linkedlist.LinkedList_pusht(_self, _node)

def LinkedList_pushv(_self, _value, _vsize):
    return _linkedlist.LinkedList_pushv(_self, _value, _vsize)

def LinkedList_pushvt(_self, _value, _vsize):
    return _linkedlist.LinkedList_pushvt(_self, _value, _vsize)

def LinkedList_pop(_self):
    return _linkedlist.LinkedList_pop(_self)

def LinkedList_popt(_self):
    return _linkedlist.LinkedList_popt(_self)

def LinkedList_remove(_self, _i):
    return _linkedlist.LinkedList_remove(_self, _i)

def LinkedList_removet(_self, _i):
    return _linkedlist.LinkedList_removet(_self, _i)

def LinkedList_isEmpty(_self):
    return _linkedlist.LinkedList_isEmpty(_self)

def LinkedList_isEmptyt(_self):
    return _linkedlist.LinkedList_isEmptyt(_self)

def LinkedList_getSize(_self):
    return _linkedlist.LinkedList_getSize(_self)

def LinkedList_getSizet(_self):
    return _linkedlist.LinkedList_getSizet(_self)


