.TH "h_echo_t" 3 "Version v01.01r" "libcnet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
h_echo_t
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ip\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "u_int16_t \fB_id\fP"
.br
.RI "16 bit for the identifier of the echo or echo reply "
.ti -1c
.RI "u_int16_t \fB_seqnum\fP"
.br
.RI "16 bit for the sequence number "
.in -1c
.SH "Detailed Description"
.PP 
Part of the ICMP Header reserved for Echo-like requests and responses 
.PP
Definition at line \fB150\fP of file \fBip\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "u_int16_t _id"

.PP
16 bit for the identifier of the echo or echo reply 
.PP
Definition at line \fB153\fP of file \fBip\&.h\fP\&.
.SS "u_int16_t _seqnum"

.PP
16 bit for the sequence number 
.PP
Definition at line \fB154\fP of file \fBip\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcnet from the source code\&.
