.TH "h_mtu_t" 3 "Version v01.02d0" "libcnet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
h_mtu_t
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ip\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "u_int16_t \fB_unused\fP"
.br
.RI "Set to zeros\&. "
.ti -1c
.RI "u_int16_t \fB_mtu\fP"
.br
.RI "Next hop MTU\&. "
.in -1c
.SH "Detailed Description"
.PP 
Part of the ICMP Header reserved for Maximum Transmission Unit 
.PP
Definition at line \fB153\fP of file \fBip\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "u_int16_t _mtu"

.PP
Next hop MTU\&. 
.PP
Definition at line \fB156\fP of file \fBip\&.h\fP\&.
.SS "u_int16_t _unused"

.PP
Set to zeros\&. 
.PP
Definition at line \fB155\fP of file \fBip\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcnet from the source code\&.
