.TH "IcmpPacket" 3 "Version v02.01d0" "libcnet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IcmpPacket
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ip\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBIcmpHeader\fP \fB_icmphdr\fP"
.br
.RI "The ICMP Header\&. "
.ti -1c
.RI "char * \fB_payload\fP"
.br
.RI "The payload containing all the ICMP data\&. "
.ti -1c
.RI "size_t \fB__size\fP"
.br
.RI "The size of the payload\&. "
.in -1c
.SH "Detailed Description"
.PP 
Struct representing the ICMP Packet with 8 bytes of Header and Payload 
.PP
Definition at line \fB176\fP of file \fBip\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "size_t __size"

.PP
The size of the payload\&. 
.PP
Definition at line \fB182\fP of file \fBip\&.h\fP\&.
.SS "\fBIcmpHeader\fP _icmphdr"

.PP
The ICMP Header\&. 
.PP
Definition at line \fB179\fP of file \fBip\&.h\fP\&.
.SS "char* _payload"

.PP
The payload containing all the ICMP data\&. 
.PP
Definition at line \fB180\fP of file \fBip\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcnet from the source code\&.
