.TH "IcmpParameters" 3 "Version v01.01r" "libcnet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IcmpParameters
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sender\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "u_int16_t \fB_id\fP"
.br
.RI "The Identification number to put into the ICMP Packet\&. "
.ti -1c
.RI "u_int16_t \fB_sn\fP"
.br
.RI "The Sequence number to put into the ICMP Packet\&. "
.in -1c
.SH "Detailed Description"
.PP 
Struct containing some parameters, like identificaton and sequence number useful when constructing ICMP Packets from the sender 
.PP
Definition at line \fB60\fP of file \fBsender\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "u_int16_t _id"

.PP
The Identification number to put into the ICMP Packet\&. 
.PP
Definition at line \fB62\fP of file \fBsender\&.h\fP\&.
.SS "u_int16_t _sn"

.PP
The Sequence number to put into the ICMP Packet\&. 
.PP
Definition at line \fB63\fP of file \fBsender\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcnet from the source code\&.
