.TH "IpHeader" 3 "Version v01.01r" "libcnet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IpHeader
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ip\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "u_int8_t \fB_version\fP"
.br
.RI "Version of IP protocol\&. "
.ti -1c
.RI "u_int8_t \fB_dsf\fP"
.br
.RI "Differentiated Service Field\&. "
.ti -1c
.RI "u_int16_t \fB_tlength\fP"
.br
.RI "Total len of IP datagram or IP fragment\&. "
.ti -1c
.RI "u_int16_t \fB_id\fP"
.br
.RI "Unique fragment identifier\&. "
.ti -1c
.RI "u_int16_t \fB_flag_off\fP"
.br
.RI "IP Flags and Fragment Offset\&. "
.ti -1c
.RI "u_int8_t \fB_ttl\fP"
.br
.RI "Time To Live\&. "
.ti -1c
.RI "u_int8_t \fB_protocol\fP"
.br
.RI "Protocol\&. "
.ti -1c
.RI "u_int16_t \fB_hdr_chksum\fP"
.br
.RI "Header Checksum\&. "
.ti -1c
.RI "u_int32_t \fB_srcaddr\fP"
.br
.RI "Source Address\&. "
.ti -1c
.RI "u_int32_t \fB_dstaddr\fP"
.br
.RI "Destination Address\&. "
.in -1c
.SH "Detailed Description"
.PP 
Struct representing the IP Header of the IP Packet\&. It consists of classical 28 bytes divided into:
.PP
.IP "\(bu" 2
\fR_version\fP, IP Protocol Version + IHL (8 bits)
.IP "\(bu" 2
\fR_dsf\fP, Type of service (8 bits)
.IP "\(bu" 2
\fR_tlength\fP, Total length (16 bits)
.IP "\(bu" 2
\fR_id\fP, Identification (16 bits)
.IP "\(bu" 2
\fR_flag_off\fP, Flags and Fragment Offset (16 bits)
.IP "\(bu" 2
\fR_ttl\fP, Time to Live (8 bits)
.IP "\(bu" 2
\fR_protocol\fP, IP Protocol (8 bits)
.IP "\(bu" 2
\fR_hdr_chksum\fP, Checksum (16 bits)
.IP "\(bu" 2
\fR_srcaddr\fP, Source Address (32 bits)
.IP "\(bu" 2
\fR_dstaddr\fP, Destination Address (32 bits)\&.
.PP
.PP
This structure refers to the RFC 791 https://datatracker.ietf.org/doc/html/rfc791 The TOS field has been subtituted with the Differentiated Service Field according to the RFC 2474 https://datatracker.ietf.org/doc/html/rfc2474 
.PP
Definition at line \fB937\fP of file \fBip\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "u_int8_t _dsf"

.PP
Differentiated Service Field\&. 
.PP
Definition at line \fB941\fP of file \fBip\&.h\fP\&.
.SS "u_int32_t _dstaddr"

.PP
Destination Address\&. 
.PP
Definition at line \fB949\fP of file \fBip\&.h\fP\&.
.SS "u_int16_t _flag_off"

.PP
IP Flags and Fragment Offset\&. 
.PP
Definition at line \fB944\fP of file \fBip\&.h\fP\&.
.SS "u_int16_t _hdr_chksum"

.PP
Header Checksum\&. 
.PP
Definition at line \fB947\fP of file \fBip\&.h\fP\&.
.SS "u_int16_t _id"

.PP
Unique fragment identifier\&. 
.PP
Definition at line \fB943\fP of file \fBip\&.h\fP\&.
.SS "u_int8_t _protocol"

.PP
Protocol\&. 
.PP
Definition at line \fB946\fP of file \fBip\&.h\fP\&.
.SS "u_int32_t _srcaddr"

.PP
Source Address\&. 
.PP
Definition at line \fB948\fP of file \fBip\&.h\fP\&.
.SS "u_int16_t _tlength"

.PP
Total len of IP datagram or IP fragment\&. 
.PP
Definition at line \fB942\fP of file \fBip\&.h\fP\&.
.SS "u_int8_t _ttl"

.PP
Time To Live\&. 
.PP
Definition at line \fB945\fP of file \fBip\&.h\fP\&.
.SS "u_int8_t _version"

.PP
Version of IP protocol\&. 
.PP
Definition at line \fB940\fP of file \fBip\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcnet from the source code\&.
