.TH "IpParameters" 3 "Version v02.01d0" "libcnet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IpParameters
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sender\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fB_xf\fP"
.br
.RI "The X flag (not used so it must be always 0) "
.ti -1c
.RI "int \fB_df\fP"
.br
.RI "Don't Fragment Flag\&. "
.ti -1c
.RI "int \fB_mf\fP"
.br
.RI "More Fragment Flag\&. "
.in -1c
.SH "Detailed Description"
.PP 
Struct containing some parameters not configurable when sending Packets Notice that D flag and M flag are mutually exclusive\&. 
.PP
Definition at line \fB29\fP of file \fBsender\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "int _df"

.PP
Don't Fragment Flag\&. 
.PP
Definition at line \fB32\fP of file \fBsender\&.h\fP\&.
.SS "int _mf"

.PP
More Fragment Flag\&. 
.PP
Definition at line \fB33\fP of file \fBsender\&.h\fP\&.
.SS "int _xf"

.PP
The X flag (not used so it must be always 0) 
.PP
Definition at line \fB31\fP of file \fBsender\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcnet from the source code\&.
