.TH "Node" 3 "Version v02.01d0" "libcnet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Node
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <list\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBNode\fP * \fB_next\fP"
.br
.RI "A pointer to the next value in the linked list\&. "
.ti -1c
.RI "struct \fBNode\fP * \fB_prev\fP"
.br
.RI "A pointer to the previous value in the linked list\&. "
.ti -1c
.RI "void * \fB_value\fP"
.br
.RI "The current value\&. "
.in -1c
.SH "Detailed Description"
.PP 
Just a single node inside a Linked List\&. 
.PP
Definition at line \fB19\fP of file \fBlist\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "struct \fBNode\fP* _next"

.PP
A pointer to the next value in the linked list\&. 
.PP
Definition at line \fB22\fP of file \fBlist\&.h\fP\&.
.SS "struct \fBNode\fP* _prev"

.PP
A pointer to the previous value in the linked list\&. 
.PP
Definition at line \fB23\fP of file \fBlist\&.h\fP\&.
.SS "void* _value"

.PP
The current value\&. 
.PP
Definition at line \fB24\fP of file \fBlist\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcnet from the source code\&.
