.TH "Response" 3 "Version v02.01d0" "libcnet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Response
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <receiver\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fB_buffer\fP"
.br
.RI "The buffer containing the received IP Packet\&. "
.ti -1c
.RI "size_t \fB_size\fP"
.br
.RI "The length of the entire buffer\&. "
.ti -1c
.RI "double \fB_rtt\fP"
.br
.RI "Essentially the Round-Trip-Time\&. "
.in -1c
.SH "Detailed Description"
.PP 
A simple struct containing the response received by the receiver 
.PP
Definition at line \fB62\fP of file \fBreceiver\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "char* _buffer"

.PP
The buffer containing the received IP Packet\&. 
.PP
Definition at line \fB65\fP of file \fBreceiver\&.h\fP\&.
.SS "double _rtt"

.PP
Essentially the Round-Trip-Time\&. 
.PP
Definition at line \fB67\fP of file \fBreceiver\&.h\fP\&.
.SS "size_t _size"

.PP
The length of the entire buffer\&. 
.PP
Definition at line \fB66\fP of file \fBreceiver\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcnet from the source code\&.
