.TH "TcpPacket" 3 "Version v01.01r" "libcnet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TcpPacket
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ip\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBTcpHeader\fP \fB_hdr\fP"
.br
.RI "TCP Header\&. "
.ti -1c
.RI "char * \fB_payload\fP"
.br
.RI "TCP Payload\&. "
.ti -1c
.RI "size_t \fB__size\fP"
.br
.RI "TCP Payload size\&. "
.in -1c
.SH "Detailed Description"
.PP 
This structure represents the TCP Packet with the Header and Payload 
.PP
Definition at line \fB597\fP of file \fBip\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "size_t __size"

.PP
TCP Payload size\&. 
.PP
Definition at line \fB602\fP of file \fBip\&.h\fP\&.
.SS "\fBTcpHeader\fP _hdr"

.PP
TCP Header\&. 
.PP
Definition at line \fB600\fP of file \fBip\&.h\fP\&.
.SS "char* _payload"

.PP
TCP Payload\&. 
.PP
Definition at line \fB601\fP of file \fBip\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcnet from the source code\&.
