.TH "UdpPacket" 3 "Version v01.02d0" "libcnet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UdpPacket
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ip\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBUdpHeader\fP \fB_hdr\fP"
.br
.RI "The UDP Header\&. "
.ti -1c
.RI "char * \fB_payload\fP"
.br
.RI "The payload\&. "
.in -1c
.SH "Detailed Description"
.PP 
This struct represents the entire UDP Packet (Header + Payload) as according to the RFC 768 https://datatracker.ietf.org/doc/html/rfc768 
.PP
Definition at line \fB412\fP of file \fBip\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBUdpHeader\fP _hdr"

.PP
The UDP Header\&. 
.PP
Definition at line \fB415\fP of file \fBip\&.h\fP\&.
.SS "char* _payload"

.PP
The payload\&. 
.PP
Definition at line \fB416\fP of file \fBip\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcnet from the source code\&.
