.TH "includes/utils/version.h" 3 "Version v01.02d0" "libcnet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/utils/version.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLIBCNET_VERSION\fP   'v\&.02\&.01d'"
.br
.ti -1c
.RI "#define \fBLIBCNET_MAJOR\fP   2"
.br
.ti -1c
.RI "#define \fBLIBCNET_MINOR\fP   1"
.br
.ti -1c
.RI "#define \fBLIBCNET_LEVEL\fP   1"
.br
.ti -1c
.RI "#define \fBLIBCNET_VERSION_HEX\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LIBCNET_LEVEL   1"

.PP
Definition at line \fB8\fP of file \fBversion\&.h\fP\&.
.SS "#define LIBCNET_MAJOR   2"

.PP
Definition at line \fB6\fP of file \fBversion\&.h\fP\&.
.SS "#define LIBCNET_MINOR   1"

.PP
Definition at line \fB7\fP of file \fBversion\&.h\fP\&.
.SS "#define LIBCNET_VERSION   'v\&.02\&.01d'"

.PP
Definition at line \fB4\fP of file \fBversion\&.h\fP\&.
.SS "#define LIBCNET_VERSION_HEX"
\fBValue:\fP
.nf
                             (  (LIBCNET_MAJOR << 16) \\
                             | (LIBCNET_MINOR << 8)  \\
                             | (LIBCNET_LEVEL << 4))
.PP
.fi

.PP
Definition at line \fB12\fP of file \fBversion\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libcnet from the source code\&.
